all: vendor/libucl/libucl.dll
	go build

clean:
	rm -rf vendor/
	rm -f libucl.dll

test: vendor/libucl/libucl.dll
	go test

vendor/libucl/libucl.dll:
	./scripts/build_libucl.sh

.PHONY: all clean test
